storage:
  postgres:
    postgres_db:
      username: dagster
      password: dagster
      hostname: postgres
      db_name: dagster
      port: 5432

local_artifact_storage:
  base_dir: /opt/dagster/dagster_home/storage

run_launcher:
  module: dagster_celery
  class: CeleryRunLauncher
  config:
    broker: amqp://dagster:dagster@rabbitmq:5672//
    backend: rpc://
    include_paths:
      - my_project  # Adjust to your repo/module path

compute_logs:
  module: dagster.core.storage.local_compute_log_manager
  class: LocalComputeLogManager
  config:
    base_dir: /opt/dagster/dagster_home/logs

scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler